package com.delivery.entity;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * @Date 2020-10-30 11:53
 *
 * @author Yvan
 */

@Data
@Entity
@Table ( name ="customer_work_order" )
public class CustomerWorkOrder implements Serializable {

	private static final long serialVersionUID = 8013393156483901401L;

 	@Column(name = "id" )
	@Id
	@GeneratedValue
	private Integer id;

	/**
	 * 工单自动生成id
	 */
 	@Column(name = "work_order_uuid" )
	private String workOrderUuid;

	/**
	 * 客户id

	 */
 	@Column(name = "customer_id" )
	private Integer customerId;

	/**
	 * 取件地址id
	 */
 	@Column(name = "pickup_address_id" )
	private Integer pickupAddressId;

	/**
	 * 送达地址id
	 */
 	@Column(name = "receive_address_id" )
	private Integer receiveAddressId;

	/**
	 * 生成时间
	 */
 	@Column(name = "create_time" )
	private Date createTime;

	/**
	 * 是否完成
	 */
 	@Column(name = "consummation" )
	private Integer consummation;

}
