package com.delivery.entity;


import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * generated by Generate POJOs.groovy 
 * @Date 2020-10-30 11:54
 *
 * @author Yvan
 */

@Data
@Entity
@Table ( name ="customer_receive_address" )
public class CustomerReceiveAddress implements Serializable {

	private static final long serialVersionUID = 5399137689634884080L;

	/**
	 * 自增id

	 */
 	@Column(name = "id" )
	@Id
	@GeneratedValue
	private Integer id;

	/**
	 * 关联的用户id
	 */
 	@Column(name = "customer_id" )
	private Integer customerId;

	/**
	 * 收货人姓名

	 */
 	@Column(name = "receive_name" )
	private String receiveName;

	/**
	 * 省id
	 */
 	@Column(name = "receive_province_id" )
	private String receiveProvinceId;

	/**
	 * 市id
	 */
 	@Column(name = "receive_city_id" )
	private String receiveCityId;

	/**
	 * 区id
	 */
 	@Column(name = "receive_area_id" )
	private String receiveAreaId;

	/**
	 * 收件详细地址
	 */
 	@Column(name = "receive_detailed_address" )
	private String receiveDetailedAddress;

	/**
	 * 状态

	 */
 	@Column(name = "del" )
	private Integer del;


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CustomerReceiveAddress)) {
            return false;
        }
        CustomerReceiveAddress that = (CustomerReceiveAddress) o;
        return Objects.equals(getCustomerId(), that.getCustomerId()) &&
                Objects.equals(getReceiveName(), that.getReceiveName()) &&
                Objects.equals(getReceiveProvinceId(), that.getReceiveProvinceId()) &&
                Objects.equals(getReceiveCityId(), that.getReceiveCityId()) &&
                Objects.equals(getReceiveAreaId(), that.getReceiveAreaId()) &&
                Objects.equals(getReceiveDetailedAddress(), that.getReceiveDetailedAddress());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCustomerId(), getReceiveName(), getReceiveProvinceId(), getReceiveCityId(), getReceiveAreaId(), getReceiveDetailedAddress());
    }
}
