package com.delivery.entity;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * generated by Generate POJOs.groovy 
 * @Date 2020-11-04 10:36
 *
 * @author Yvan
 */

@Data
@Entity
@Table ( name ="customer_address" )
public class CustomerAddress implements Serializable {

	private static final long serialVersionUID = 7697795937326459187L;

 	@Column(name = "id" )
	@Id
	@GeneratedValue
	private Integer id;

	/**
	 * 省id
	 */
 	@Column(name = "province_id" )
	private String provinceId;

	/**
	 * 市id
	 */
 	@Column(name = "city_id" )
	private String cityId;

	/**
	 * 区id
	 */
 	@Column(name = "area_id" )
	private String areaId;

	/**
	 * 用户详细地址
	 */
 	@Column(name = "address_detail" )
	private String addressDetail;

	/**
	 * 用户id
	 */
 	@Column(name = "user_id" )
	private Integer userId;

	/**
	 * 0 为删除 1 删除
	 */
 	@Column(name = "del" )
	private Integer del;

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CustomerAddress)) {
            return false;
        }
        CustomerAddress that = (CustomerAddress) o;
        return Objects.equals(getProvinceId(), that.getProvinceId()) &&
                Objects.equals(getCityId(), that.getCityId()) &&
                Objects.equals(getAreaId(), that.getAreaId()) &&
                Objects.equals(getAddressDetail(), that.getAddressDetail()) &&
                Objects.equals(getUserId(), that.getUserId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getProvinceId(), getCityId(), getAreaId(), getAddressDetail(), getUserId());
    }
}
