package com.delivery.entity;

import java.io.Serializable;
import lombok.Data;

import javax.persistence.*;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * @Date 2020-10-23 13:16
 *
 * @author Yvan
 */

@Data
@Entity
@Table ( name ="customer" )
public class Customer implements Serializable {

	private static final long serialVersionUID = 4332708456854172667L;

 	@Column(name = "id" )
	@Id
	@GeneratedValue
	private Integer id;

	/**
	 * 电话
	 */
 	@Column(name = "phone" )
	private String phone;

	/**
	 * 密码
	 */
 	@Column(name = "password" )
	private String password;

	/**
	 * 用户名
	 */
 	@Column(name = "name" )
	private String name;

	/**
	 * 用户邮箱
	 */
 	@Column(name = "customer_email" )
	private String customerEmail;

	/**
	 * 创建时间
	 */
 	@Column(name = "create_time" )
	private Date createTime;

	/**
	 * 0表示女，1表示男
	 */
 	@Column(name = "sex" )
	private Integer sex;

}
